### ISSUE TITLE
If an error occurs the pod gets OOMkilled

### ISSUE THREAD

**Issue by jeroenvermeulen** [paulrostorp/bunnycdn-operator#2]
Example:
```
---
apiVersion: bunny-cdn-operator.com/v1alpha1
kind: PullZone
metadata:
  name: test.something.else # => This is wrong
  namespace: default
spec:
  originUrl: https://google.com
  deletionPolicy: delete
```

The problem is caused by the logger from the `winston-logfmt` going into an endless loop.
